[feat] : 질문 폼의 모든 리뷰어 조회- 인수테스트 작성
depromeet/na-lab-server pull request #120
Opened 2023-05-25 17:51 UTC by ssssujini99

## 어떤 기능을 개발했나요?
질문 폼의 모든 리뷰어 조회 API에 대한 인수테스트를 작성했습니다

- [x]  /feedback/findreviewers 패키지에 **질문 폼의 모든 리뷰어 조회** `인수테스트` 클래스를 생성했습니다
- [x] `FeedbackAcceptanceValidator` 에 요청로직에 대한 validation 로직을 추가했습니다 -> `assertIsReviewersNotFound`, `assertIsReviewersFound`
* 피드백이 하나도 없는 경우일때 , 피드백이 하나라도 있는 경우일 때 두 가지로 나누어서 검증을 하였습니다

- [x] `AbstractFeedbackTestSupporter` 에 요청로직을 추가했습니다 -> `findReviewers` 

## 어떻게 해결했나요?

## 참고자료

2023-05-25 17:54 UTC, ssssujini99 commented
질문폼생성 - 해당질문폼에응답 이 부분을 common으로 빼면 좋을 것 같아요
이게 계속 중복이 일어나네요 ㅠ_ㅠ 리팩토링때 하면 좋을 것 같습니다!!

2023-05-26 02:10 UTC, devxb requested changes

2023-05-26 02:10 UTC, devxb commented on api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
> +			jsonPath("$.feedbacks[0].created_at").isNotEmpty(),
의도된 notEmpty 인가요??
createdAt은 배열이 아니라? notEmpty말고 isString으로 검증하는건 어떤가요??
``` json
{
    "feedbacks": [
        {
            "feedback_id": 5,
            "created_at": "2023-01-24T12:00:00",
            "reviwer": {
                "nickname": "A",
                "collaboration_experience": true,
                "position": "developer"
            },
            "is_read": false
        }
    ]
}
```

2023-05-26 02:10 UTC, devxb commented on api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/findreviewers/ReviewersFindAcceptanceTest.java
> +		FeedbackCreateRequest feedbackCreateRequest = getFeedbackCreateRequest(surveyFindResponse, true, "developer");
position 인자를 `programmer` 로 꿔야할거 같아요!
developer가 들어오면 validation fail이 뜰거같습니다!

아래는 선택가능한? validation 목록이에요
``` java
@Pattern(regexp = "^(designer|product-manager|programmer|other)$")
```

2023-05-26 06:51 UTC, devxb approved these changes

2023-05-26 06:53 UTC, merged