[feat] : 질문 폼의 모든 리뷰어 목록 조회 application 구현
depromeet/na-lab-server pull request #121
Opened 2023-05-25 19:29 UTC by ssssujini99

## 어떤 기능을 개발했나요?
- [x] in port 에서 질문 폼의 리뷰어 목록 조회 유즈케이스의 interface인 `FeedbackReviewersFindUseCase` 정의하고, 이의 구현체 를 만들었습니다
- [x] 그리고 이의 테스트를 구현하였습니다 - 테스트는 리뷰가 없는 경우 / 있는 경우 로 나누었습니다 
- [x] out persistence 에서 port 인터페이스를 정의하였습니다

## 어떻게 해결했나요?

## 참고자료

2023-05-25 22:10 UTC, ssssujini99 commented
아.... 과제 다끝나고 맘급하게 하는바람에 또 pr단위가 너무 커저버렸습니다 ... 🥺
이제 api 1개 남았습니다 ,,, 조금만 자고 다시 돌아오겠습니다
인수테스트부터 확인해주시면 감사하겠습니다!!

2023-05-26 02:23 UTC, devxb requested changes
review 단위로 커밋하시고 코멘트로 커밋 해쉬값 올려주시면 감사하겠습니다 👍

2023-05-26 02:23 UTC, devxb commented on survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/feedbackreviewers/FeedbacksFindPort.java
> +	List<FeedbackDto> findAllFeedback(Long surveyId);
여기는 out.port니까 Feedbakc dto가 아니라 domain을 반환해야 할거같아요

domain을 받아서 service에서 매핑해주는 방식으로 정했던거로 기억합니다!

2023-05-26 02:23 UTC, devxb commented on survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/FeedbacksReviewersAdaptor.java
> +import me.nalab.survey.application.common.feedback.mapper.FeedbackDtoMapper;
```suggestion
```

jpa-adaptor에서, application에 대한 참조는 out.port로만 가도록? 하는거 어떤가요??

2023-05-26 02:23 UTC, devxb commented on survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/FeedbacksReviewersAdaptor.java
> +			.collect(Collectors.toList());
```suggestion
		return feedbackEntities.stream()
			.map(FeedbackEntityMapper::toDomain)
			.collect(Collectors.toList());
```

2023-05-26 02:23 UTC, devxb commented on survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/FeedbacksReviewersAdaptor.java
> +	public List<FeedbackDto> findAllFeedback(Long surveyId) {
```suggestion
	public List<Feedback> findAllFeedback(Long surveyId) {
```

2023-05-26 02:23 UTC, devxb commented on survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/FeedbacksReviewersAdaptorTest.java
> +		FeedbackEntity feedbackEntity2 = FeedbackEntityMapper.toEntity(feedback2);
제안) 
배열로 바꾸는건 어떤가요

2023-05-26 02:23 UTC, devxb commented on survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/FeedbackReviewersController.java
> +	public ResponseEntity<FeedbackReviewersResponse> getFeedbackReviewers(@RequestParam("survey-id") Long surveyId) {
이거 ResponseEntity로 내려주는거랑 `@ResponseStatus` 쓰는거 컨벤션도 맞춰야할거 같아요 (리팩토링때)

저는 controller를 아래처럼 만들어놔서요..!
``` java
@ResponseStatus(HttpStatus.OK)
```

2023-05-26 02:23 UTC, devxb commented on survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/response/ReviewerResponse.java
> +	private String nickname;
```suggestion
	@JsonProperty("nickname")
	private String nickName;
```

2023-05-26 02:23 UTC, devxb commented on survey/web-adaptor/src/test/java/me/nalab/survey/web/adaptor/feedbackreviewers/FeedbackReviewersResponseMapperTest.java
> +class FeedbackReviewersResponseMapperTest {
이거 스킵하셔도 되는데 작성하셨네요! 👍👍 
꼼꼼한거 너무 좋습니다

2023-05-26 02:24 UTC, devxb commented
> 아.... 과제랑 팀플 다끝내고 맘급하게 하는바람에 또 pr단위가 너무 커져버렸습니다 ... 🥺
> 이제 api 1개 남았습니다 ,,, 조금만 자고 다시 돌아오겠습니다
> 인수테스트부터 확인해주시면 감사하겠습니다!!

인수테스트가...! 없는거 같아요 확인 부탁드려요

2023-05-26 03:45 UTC, ssssujini99 commented on survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/FeedbackReviewersController.java
> +	public ResponseEntity<FeedbackReviewersResponse> getFeedbackReviewers(@RequestParam("survey-id") Long surveyId) {
넵 좋아요 ㅎㅎ

2023-05-26 06:42 UTC, ssssujini99 commented on survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/feedbackreviewers/FeedbacksFindPort.java
> +	List<FeedbackDto> findAllFeedback(Long surveyId);
[cf02b43](https://github.com/depromeet/na-lab-server/pull/121/commits/cf02b43363f791be37addb5010dc0933cfeeb99d)

2023-05-26 06:42 UTC, ssssujini99 commented on survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/FeedbacksReviewersAdaptor.java
> +			.collect(Collectors.toList());
[cf02b43](https://github.com/depromeet/na-lab-server/pull/121/commits/cf02b43363f791be37addb5010dc0933cfeeb99d)

2023-05-26 06:42 UTC, ssssujini99 commented on survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/FeedbacksReviewersAdaptor.java
> +	public List<FeedbackDto> findAllFeedback(Long surveyId) {
[cf02b43](https://github.com/depromeet/na-lab-server/pull/121/commits/cf02b43363f791be37addb5010dc0933cfeeb99d)

2023-05-26 06:43 UTC, ssssujini99 commented on survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/FeedbacksReviewersAdaptor.java
> +import me.nalab.survey.application.common.feedback.mapper.FeedbackDtoMapper;
[1846dbc](https://github.com/depromeet/na-lab-server/pull/121/commits/1846dbce1b2c8b702a28ed316a5dbe906339915f)

2023-05-26 06:43 UTC, ssssujini99 commented on survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/response/ReviewerResponse.java
> +	private String nickname;
[8f7e429](https://github.com/depromeet/na-lab-server/pull/121/commits/8f7e4295082c0caa9648cb7cabca1b65fa033d68)

2023-05-26 06:44 UTC, ssssujini99 commented on survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/FeedbacksReviewersAdaptorTest.java
> +		FeedbackEntity feedbackEntity2 = FeedbackEntityMapper.toEntity(feedback2);
저기서 dto는 지워졌어요..!!
근데 나머지 각각의 엔티티와 도메인은 각각이 필요해서 정의가 필요합니다 🥺

2023-05-26 06:52 UTC, devxb approved these changes

2023-05-26 06:53 UTC, merged