[test] : feedback 조회 ece test
depromeet/na-lab-server pull request #279
Opened 2023-06-22 12:09 UTC by ssssujini99

## 어떤 기능을 개발했나요?
피드백을 조회하는 ece test를 만들었습니다

## 어떻게 해결했나요?
- [x] 로그인
- [x] survey 생성
- [x] survey 조회 및 feedback 생성을 위한 id값들 저장
- [x] feedback 생성
- [x] 질문 폼의 모든 피드백 조회 및 개별 피드백 조회를 위한 feedback_id 저장
- [x] 개별 피드백 응답 조회

## 이슈 넘버
- #275 

## (option) 어떤 부분에 집중하여 리뷰해야 할까요?

- [ ] 질문 폼의 모든 리뷰어 목록 조회
- [ ] 질문 폼에 리뷰한 리뷰어 정보 요약 조회
- [ ] 질문 폼의 전체 피드백 수와 읽지 않은 피드백 조회

이 나머지 API들도 한번에 같이 올릴까요?
일단은 큰 시나리오 내에서만 확인할 API만 추가했는데, 나머지들도 한꺼번에 다 넣을지 고민입니다..!!

## 참고자료
https://hurl.dev/docs/asserting-response.html#jsonpath-assert

2023-06-23 02:56 UTC, devxb commented
음,, 저것도 한번에 하는게 좋을거 같아요! 👍
수고하셨습니다~

2023-06-23 07:41 UTC, devxb commented
https://depromeet13th.slack.com/archives/C0515QNLVHB/p1687505945320449

슬랙에 ci 관련해서 수정사항 올렸습니다.! 이것만 수정해주세요

2023-06-23 07:50 UTC, ssssujini99 commented
넵! 수정하고 피드백관련 나머지api들도 다같이 올려놓겠습니다~

2023-06-26 12:52 UTC, devxb approved these changes

2023-06-26 12:52 UTC, devxb requested changes
feedback_find를 3_으로 변경해주세요

2023-06-27 03:09 UTC, merged