[feat] : target, bookmark 엔티티 업데이트
depromeet/na-lab-server pull request #291
Opened 2023-07-03 13:23 UTC by ssssujini99

## 어떤 기능을 개발했나요?
2차 mvp에 추가되는 엔티티의 업데이트내용을 반영하고, flyway에 v4를 추가하였습니다

## 어떻게 해결했나요?

- [x] `FormFeedbackEntity`에 `isBookmarked` 필드를 추가했습니다
- [x] flyway v4에 해당 내용을 업데이트하고, 기존에 있는 데이터들은 `false`로 세팅되게끔 하였습니다

- 그리고 mapper 변경사항은 그리고 도메인, 엔티티 각 부분 merge후에 수정하면 될 것 같습니다.

## 이슈 넘버
- close #290 

## 참고자료

2023-07-03 13:36 UTC, devxb requested changes
엔티티에서 bookmark에 대한 날짜 ex. `bookmaredAt` 도 추가로 필요할거같아
이유는, feedback이 생성된 날짜랑 bookmarked된 날짜랑 다를 수 있으니까?

2023-07-04 00:23 UTC, devxb commented on api/src/main/resources/db/migration/V4__add_bookmark.sql
> +ALTER TABLE form_feedback ADD bookmarked_at timestamp(6);
default값 안줘도 되나??

이거 논의해봐야할듯!
1. bookmarked 된적이 없다면 null 처리?
2. feedback 생성날짜를 bookmarkedAt default로?

2023-07-04 00:37 UTC, devxb commented on api/src/main/resources/db/migration/V4__add_bookmark.sql
> +ALTER TABLE form_feedback ADD bookmarked_at timestamp(6);
질문)

ALTER TABLE ... 에 default로 값 넣어주면 `이미 삽입되어있던` 데이터들에도 default값으로 바인딩 되는거야??
저 default값이 바인딩 되는 시점이 궁금

2023-07-04 08:33 UTC, ssssujini99 commented on api/src/main/resources/db/migration/V4__add_bookmark.sql
> +ALTER TABLE form_feedback ADD bookmarked_at timestamp(6);
응응 그래서 기존 데이터들에 대해서는 is_bookmarked는 false로 넣어줘야된다고 생각했고, 그래서 is_bookmarked는 nullable=false로 걸었어! 무조건 값이 바인딩되어있게끔
그리고 bookmarked_at은 최신 북마크가 된(true 또는 false) 시간을 넣어줘야되는데, 기존 데이터들 그리고 처음 추가된 피드백들에 대해서는 null이어야 하고, 한 번이라도 북마크가 되면? 그때 시간을 바인딩해줘야된다고 생각했어 그래서 얘는 nullable=false를 걸어주지 않았어!
음 나두 이거 이따 같이 얘기해보면 좋을 것 같애~!!

2023-07-04 14:52 UTC, devxb approved these changes

2023-07-04 14:52 UTC, merged