[feat] : 질문폼의 북마크된 피드백 교체 - `application` 추가
depromeet/na-lab-server pull request #304
Opened 2023-07-07 17:31 UTC by ssssujini99

## 어떤 기능을 개발했나요?

`질문폼의 북마크된 피드백 교체` API에 대한 application 부분을 개발 완료했습니다

- [x] in port 에서 **질문폼의 북마크된 피드백 교체** 유즈케이스의 interface인 `BookmarkReplaceUseCase` 정의하고, 이의 구현체 를 만들었습니다
- [x] out persistence 에서 port 인터페이스를 정의하였습니다
- [x] 구현체에서 발생할 수 있는 예외 클래스를 작성했습니다 - `FormQuestionFeedbackNotExistException`
- [x] 그리고 이의 테스트를 구현하였습니다 - 테스트는 예외 케이스까지 모두 검증하였습니다

## 어떻게 해결했나요?

## 참고자료

2023-07-07 18:02 UTC, ssssujini99 commented
bookmark에 대해 @PrePersist, @PostPersist 추가했는데,
jpa-adpator test쪽에서 피드백 생성하고 생성한 피드백 조회하는 모든 테스트에서 깨지더라구요
bookmarkedAt 이 persist 되는 시점에 넣어지기 때문에, @EqualsAndHashCode 에서 not equals라 뜹니다 ,,
그래서 지우고 그냥 따로 오버라이딩해서 isBookmarked 에 대해서만 비교하도록 했는데

준영아 근데 애초에 이거 도메인에 bookmarkedAt은 없어도 되는거 아니야?
나는 도메인에는 BookmarkedAt 은 없어도 될 것 같아! isBookmarked 만 있으면 될듯? 어차피 북마크 교체되는 시점은 디비에 반영되는 시점으로 다 들어가니까
도메인이랑 application 로직단에서는 isBookmarked 만 switching 해주면 될 것 같아!

2023-07-08 01:44 UTC, dojinyou requested changes

2023-07-08 01:44 UTC, dojinyou commented on survey/survey-domain/src/main/java/me/nalab/survey/domain/feedback/Bookmark.java
> +	}
이러면 사실상 VO처럼 비교가 되서 결국 true면 다 같고 false면 다 다르고가 되어 버리는 데 이게 의도한 게 맞는 지 모르겠음! 차라리 feedback쪽에서 eqauls 동작에 Bookmark가 제외되어야 할듯?!
개인적으로는 그냥 id만 비교해도 될 거 같음

2023-07-08 01:44 UTC, dojinyou commented on survey/survey-domain/src/main/java/me/nalab/survey/domain/feedback/Bookmark.java
> +	}
`@EqualsAndHashCode(of = "id")`
`@EqualsAndHashCode(exclude = "bookmark")`
이렇게 값 넣어서 특정 값을 추가하거나 제외할 수 있음

2023-07-08 03:53 UTC, ssssujini99 commented on survey/survey-domain/src/main/java/me/nalab/survey/domain/feedback/Bookmark.java
> +	}
엉엉 그게 맞는것같다 차라리 Bookmark만 빼는게 맞는듯!! 오키

2023-07-09 06:44 UTC, dojinyou commented on survey/survey-application/src/main/java/me/nalab/survey/application/service/bookmark/ReplaceBookmarkService.java
> +		bookmark.replaceIsBookmarked();
feedBack쪽에 메서드 한번 호출하면 좋을 것 같은데 어때?

2023-07-09 06:44 UTC, dojinyou commented on survey/survey-domain/src/main/java/me/nalab/survey/domain/feedback/Bookmark.java
> +	}
[nit]
`switchBookmark()`?

그리고 북마크 바뀔 때 시간 업데이트는 안해주나연?

2023-07-09 07:17 UTC, dojinyou approved these changes

2023-07-09 07:17 UTC, dojinyou commented on survey/survey-domain/src/main/java/me/nalab/survey/domain/feedback/FormQuestionFeedbackable.java
> +	}
```suggestion
	public void switchBookmark() {
		bookmark.replaceIsBookmarked();
		bookmark.updateBookmarkedAt();
	}
```
이런 느낌?! 생각했고
updateBookmarkedAt()이 replaceBookmarked 안으로 들어가야지 외부에서 두번 호출할 필요 없이 북마크 상태 변경하고 상태 변경 시점 기록이라는 2가지 일이 하나의 원자성으로 보장되는 듯?!

2023-07-09 07:20 UTC, ssssujini99 commented on survey/survey-domain/src/main/java/me/nalab/survey/domain/feedback/FormQuestionFeedbackable.java
> +	}
아 아예 두 작업을 하나의 원자성 단위로 생각했구나

2023-07-09 07:20 UTC, ssssujini99 commented on survey/survey-domain/src/main/java/me/nalab/survey/domain/feedback/FormQuestionFeedbackable.java
> +	}
응응 나도 그게 더 맞는것같애!!

2023-07-09 07:29 UTC, merged