[feat]북마크된 피드백 조회 기능 구현 및 테스트 작성
depromeet/na-lab-server pull request #313
Opened 2023-07-09 13:43 UTC by dojinyou

## 어떤 기능을 개발했나요?
- 북마크된 피드백 조회 기능 구현
- 북마크된 피드백 조회 기능 테스트

## 이슈 넘버

issue #298

## TODO
- [ ] 북마크 스위치 기능 추가되면 인수 테스트에 추가하기

2023-07-09 14:26 UTC, ssssujini99 commented
오빠 이거 아마 모든 기능들 다 base로 한번에 합친다음에 완성된다음 main으로 한 번에 머지해야할거야! 그래야 인수테스트가 안깨져서

2023-07-10 02:47 UTC, dojinyou commented on survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/bookmark/FormQuestionFeedbackUpdateAdaptor.java
> +		FormFeedbackEntity formFeedbackEntity = formQuestionFeedbackUpdateRepository.findById(formQuestionFeedbackable.getId()).orElseThrow();
더티체크를 위해 조회를 findById로 바꿈!! 체크!

2023-07-10 02:57 UTC, ssssujini99 commented on survey/survey-application/src/main/java/me/nalab/survey/application/common/feedback/dto/BookmarkedFeedbackDto.java
이거는 왜 추가된거야?? 지금 dto들도 다 만들어져있지않나?!

2023-07-10 03:00 UTC, ssssujini99 commented on survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/bookmark/FormQuestionFeedbackUpdateAdaptor.java
> +		FormFeedbackEntity formFeedbackEntity = formQuestionFeedbackUpdateRepository.findById(formQuestionFeedbackable.getId()).orElseThrow();
근데 생각해보니까 그러면 findport의 의미가 없어지네? ㅋㅋㅋㅋㅋㅋㅋㅋ

2023-07-10 03:02 UTC, ssssujini99 commented on survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/bookmark/FormQuestionFeedbackUpdateAdaptor.java
> +		FormFeedbackEntity formFeedbackEntity = formQuestionFeedbackUpdateRepository.findById(formQuestionFeedbackable.getId()).orElseThrow();
유즈케이스에서 쟤만 호출하면 끝나는거거던

2023-07-10 03:03 UTC, dojinyou commented on survey/survey-application/src/main/java/me/nalab/survey/application/common/feedback/dto/BookmarkedFeedbackDto.java
불필요해서 삭제해버림! 5d0f92e

2023-07-10 09:10 UTC, devxb commented
PR body issue에 
- closes #298 

이렇게 걸어줘야지 자동으로 닫힐거같아

2023-07-11 00:58 UTC, devxb requested changes
저는 `@Transactional` 말고는 다 좋네용 👍 요거만 추가해주시면 될듯?!

2023-07-11 00:58 UTC, devxb commented on auth/auth-mock/src/main/java/me/nalab/auth/mock/interceptor/MockAuthInterceptor.java
> +		for (String[] excludedURI: EXCLUDED_URI_LIST) {
```suggestion
		for (String[] excludedURI : EXCLUDED_URI_LIST) {
```

: 이거 한칸 띠우는 컨벤션이 있었나..?

2023-07-11 00:58 UTC, devxb commented on auth/auth-mock/src/main/java/me/nalab/auth/mock/interceptor/MockAuthInterceptor.java
> +	};
👍👍👍

2023-07-11 00:58 UTC, devxb commented on survey/survey-application/src/main/java/me/nalab/survey/application/service/findfeedback/BookmarkedFeedbackFindService.java
> +	@Override
```suggestion
	@Override
	@Transactional(readOnly = true)
```

2023-07-11 00:58 UTC, devxb commented on survey/survey-application/src/main/java/me/nalab/survey/application/service/findfeedback/BookmarkedFeedbackFindService.java
> +	@Override
이거 여기 `@Transactional` 걸어주는게 만클아 책 컨벤션인거같아

2023-07-11 00:58 UTC, devxb commented on survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/bookmark/FormQuestionFeedbackUpdateAdaptor.java
> +		FormFeedbackEntity formFeedbackEntity = formQuestionFeedbackUpdateRepository.findById(formQuestionFeedbackable.getId()).orElseThrow();
👍

2023-07-12 13:22 UTC, devxb commented
이거 squash 부탁드림다!

2023-07-12 14:03 UTC, dojinyou commented on survey/survey-application/src/main/java/me/nalab/survey/application/service/findfeedback/BookmarkedFeedbackFindService.java
> +	@Override
5e95fc2

2023-07-12 14:18 UTC, devxb approved these changes

2023-07-12 14:18 UTC, merged