[feat] : 질문폼의 타입에 해당하는 피드백 조회 - `application` 추가
depromeet/na-lab-server pull request #331
Opened 2023-07-11 20:37 UTC by ssssujini99

## 어떤 기능을 개발했나요?

`질문폼의 타입에 해당하는 피드백 조회` API에 대한 `application` 부분을 개발 완료했습니다

- [x] in port 에서 **질문폼의 타입에 해당하는 피드백 조회** 유즈케이스의 interface인 `FeedbackFindByTypeUseCase` 정의하고, 이의 구현체 를 만들었습니다
- [x] out persistence 에서 port 인터페이스를 정의하였습니다 -  `FormQuestionFindPort`,  `FeedbackFindPort`
- [ ] survey의 질문들 중 formType에 해당하는 질문이 없는 경우에 대한 예외를 추가하였습니다 - `SurveyDoesNotHasFormTypeException`
- [x] 그리고 서비스 테스트를 추가하였습니다 - 테스트는 예외 케이스까지 모두 검증하였습니다

## 어떻게 해결했나요?

## 참고자료

2023-07-11 23:02 UTC, ssssujini99 commented
어떻게 또 로직 짜다 보니 tendency로만이 아닌 일반적인 form-type으로 짜게되더라구요...!

2023-07-12 00:37 UTC, devxb requested changes
수고많으셨습니다!

선택적으로 반영하고 재요청 날려주세요 :) 바로 누르러 올게요

2023-07-12 00:37 UTC, devxb commented on survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/findfeedback/type/FeedbackFindByTypeUseCase.java
> +	List<FormQuestionDtoable> formQuestionMatchingWithType(SurveyDto surveyDto, String formType);
질문 ✋ 

`port.in`에 정의된거로 보아서, `Controller`에서 이 인터페이스를 호출할 거 같은데,
type을 기반으로 Feedback을 찾는 컨트롤러에서 왜 이것들을 다 호출해야하는건가요??

2023-07-12 00:37 UTC, devxb commented on survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/findfeedback/type/FeedbackFindByTypeUseCase.java
> +	List<FormQuestionDtoable> formQuestionMatchingWithType(SurveyDto surveyDto, String formType);
formType은 application쪽에 전에 만들어놓은 enum으로 관리한다? 어떤가요?

2023-07-12 00:37 UTC, devxb commented on survey/survey-application/src/main/java/me/nalab/survey/application/service/findfeedback/type/FeedbackFindByTypeService.java
> +	@Transactional
```suggestion
	@Transactional(readOnly = true)
```

DB에 조회만하고 다른 동작을 하지 않는게, 맞다면 이거 걸어주는게 좋다고 생각합니다 :)

2023-07-12 00:37 UTC, devxb commented on survey/survey-application/src/main/java/me/nalab/survey/application/service/findfeedback/type/FeedbackFindByTypeService.java
> +		}
```suggestion
		Optional<Survey> survey = surveyFindPort.findSurveyById(surveyId)
			.orElseThrow(() -> {throw new SurveyDoesNotExistException(surveyId);});
```

이렇게 줄이는것도 가능해 보이네요!
Optional 사용하면, 가능하면 Optional쪽 API를 사용하자는 주의입니다!

2023-07-12 00:37 UTC, devxb commented on survey/survey-application/src/main/java/me/nalab/survey/application/service/findfeedback/type/FeedbackFindByTypeService.java
> +		}
```suggestion
		Optional<Long> targetId = targetIdFindPort.findTargetIdBySurveyId(surveyId)
			.orElseThrow(() -> {throw new SurveyDoesNotHasTargetException(surveyId);});
```

여기도 마찬가지!

2023-07-12 00:37 UTC, devxb commented on survey/survey-application/src/main/java/me/nalab/survey/application/service/findfeedback/type/FeedbackFindByTypeService.java
> +		}
(근데 꼭 할 필요는없음! 제안이라서)

2023-07-12 00:37 UTC, devxb commented on survey/survey-application/src/main/java/me/nalab/survey/application/service/findfeedback/type/FeedbackFindByTypeService.java
> +	@Transactional
```suggestion
	@Transactional(readOnly = true)
```

2023-07-12 00:37 UTC, devxb commented on survey/survey-application/src/main/java/me/nalab/survey/application/service/findfeedback/type/FeedbackFindByTypeService.java
> +			|| q instanceof ShortFormQuestionDto && ((ShortFormQuestionDto)q).getShortFormQuestionDtoType()
한눈에 의도가 보이는거 같지는 않아서.. 이 부분 메소드로 추출하는것도 좋아보이는데 어떻게 생각하시나요
(아니면, 지금은 급하니까 나중에 리팩토링때 한다?)

2023-07-12 00:37 UTC, devxb requested changes
수고많으셨습니다!

선택적으로 반영하고 재요청 날려주세요 :) 바로 누르러 올게요

2023-07-12 06:10 UTC, ssssujini99 commented on survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/findfeedback/type/FeedbackFindByTypeUseCase.java
> +	List<FormQuestionDtoable> formQuestionMatchingWithType(SurveyDto surveyDto, String formType);
생각해보니 findSurvey는 service 부분에서 private 메서드로 바꾸고 내부에서 호출하는게 좀 더 나을 것 같아서 그렇게 리팩토링했습니다! 확인 부탁드려요

그래서 최종적으로는 저 밑에 두 함수만 Controller에서 호출할 것 같습니다

2023-07-12 06:18 UTC, ssssujini99 commented on survey/survey-application/src/main/java/me/nalab/survey/application/service/findfeedback/type/FeedbackFindByTypeService.java
> +		}
다 요렇게 리팩토링했습니다! 저도 이게 더 좋은 것 같아요~

2023-07-12 06:22 UTC, ssssujini99 commented on survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/findfeedback/type/FeedbackFindByTypeUseCase.java
> +	List<FormQuestionDtoable> formQuestionMatchingWithType(SurveyDto surveyDto, String formType);
이게 type이 tendency와 같은 경우는 choice 한가지인데, custom은 choice, short 둘 다 해당이 되구 그래서 enum으로 쓰기가 어렵더라구요..!! 저도 생각했었는데
(모든 질문에 공용적인 formType으로 나눈게 아니라 도메인에서는 객관식 / 주관식 에 따라 formType 이 나눠지기 때문에..!!)
그래서 이건 그냥 formType을 String으로 받아와야할 것 같다고 생각했어요!

2023-07-12 06:23 UTC, ssssujini99 commented on survey/survey-application/src/main/java/me/nalab/survey/application/service/findfeedback/type/FeedbackFindByTypeService.java
> +			|| q instanceof ShortFormQuestionDto && ((ShortFormQuestionDto)q).getShortFormQuestionDtoType()
넵 이부분은 TODO로 남겨두고 리팩토링때 더 직관적이도록 바꿔볼게요!

2023-07-12 06:33 UTC, devxb approved these changes
🚀
수고하셨습니다!!

2023-07-12 06:47 UTC, merged