[refactor] : Survey 도메인을 kotlin으로 리팩토링한다
depromeet/na-lab-server pull request #395
Opened 2024-03-07 08:17 UTC by devxb

## 어떤 기능을 개발했나요?
Survey 도메인을 kotlin으로 리팩토링 했습니다

## 어떻게 해결했나요?
- [x] Survey 어그리거트 루트 -> Target 
	기존 도메인 열어보니 Target하나에 여러개의 Survey가 되는거로 구성되어있어서 어그리거트 루트를 Target으로 지정했습니다.
- [x] Feedback 어그리거트 루트 -> Feedback
- [x] IdGenerator와 같은 복잡한 로직 삭제 (밖에서 넣어주는게 이해하기 편할듯) 했습니다. 

## 이슈 넘버
- close #384 

## 참고자료

2024-03-08 07:56 UTC, dojinyou requested changes
일단은 기존 도메인에 있던 메서드들 다 있어야될 것 같음.

2024-03-08 07:56 UTC, dojinyou commented on src/main/kotlin/domain/feedback/value/NickName.kt
> +) {
value class 고려해도 좋을듯

2024-03-08 07:56 UTC, dojinyou commented on src/main/kotlin/domain/feedback/value/NickName.kt
> +        }
```suggestion
        fun getNextNickname(lastNickname: String?): String {
          if (lastNickname == null) {
            return "A"
          }

          if(lastNickname.last() < 'Z') {
            return lastNickname.dropLast(1).plus(lastNickname.last() + 1)
          }

          val sb = StringBuilder()
          for (i in lastNickname.lastIndex downTo  0) {
            val expectedChar = lastNickname[i] + 1
            if (expectedChar <= 'Z') {
              sb.append(expectedChar)
              sb.append(lastNickname.substring(0, i))
              break
            }

            sb.append("A")

            // 첫자리까지 Z보다 크다면 앞에 A를 추가해준다.
            if (i == 0) {
              sb.append("A")
            }
          }

          return sb.reverse().toString()
        }
```

2024-03-08 07:56 UTC, dojinyou commented on src/main/kotlin/domain/survey/Choice.kt
> +    }
```suggestion
    override fun compareTo(other: Choice) = Integer.compare(this.order, other.order)
```

2024-03-08 07:56 UTC, dojinyou commented on src/main/kotlin/domain/survey/ChoiceFormQuestion.kt
> +    }
이건 왜 추가된거지? 원래 있었나? 안 보임

2024-03-08 07:56 UTC, dojinyou commented on src/main/kotlin/domain/survey/FormQuestionable.kt
> +    override fun compareTo(other: FormQuestionable): Int {
dito

2024-03-08 07:56 UTC, dojinyou commented on src/main/kotlin/domain/survey/Survey.kt
> +    private fun validNoDuplicatedFormOrder() {
ditto

2024-03-08 07:56 UTC, dojinyou commented on src/main/kotlin/domain/survey/Target.kt
> +        private val NONE_BOOKMARKED_SURVEYS: MutableSet<SurveyBookmark> = HashSet()
?

2024-03-08 07:56 UTC, dojinyou commented on src/main/kotlin/domain/survey/value/ImageUrl.kt
> +class ImageUrl(
value class?

2024-03-09 02:47 UTC, devxb commented on src/build.gradle
> +    testRuntimeOnly "com.h2database:h2"
[9ae68b5](https://github.com/depromeet/na-lab-server/pull/395/commits/9ae68b5de6cc474d2cd3fcc4b772015595d8a68d)

gradle 최상위로 옮기면서 기존거 삭제함 
migration.gradle 만들고 거기에 필요한 의존성들 넣으면서 할 예정 나중에 한번에 찢고
(모듈로 착각해서 src안에 뒀더니 적용 의존성 적용이 안되고 있었어)

2024-03-09 03:02 UTC, devxb commented on src/main/kotlin/domain/feedback/Bookmark.kt
> +    var isBookmarked: Boolean = domain.feedback.Bookmark.Companion.BOOKMARK_DEFAULT_STATE,
[a72fa11](https://github.com/depromeet/na-lab-server/pull/395/commits/a72fa11fb0477387fefb0926fdc877ca734f6d61)

이거 패키지 잘못옮기면서 생성된듯 (me.nalab.api.survey.*) 로 가야하는데 (survey.*) 으로 옮겨서
패키지 수정하니까 싹 사라졌어

2024-03-09 03:03 UTC, devxb commented on src/main/kotlin/domain/feedback/Bookmark.kt
> +            domain.feedback.Bookmark(bookmarkedAt = TimeUtil.toInstant())
지금 정책이 ChoiceFormQuestion (객관식 질문) 에는 북마크할 수 없음. 그래서 이거 표현하려고 해놨어
기능에서 큰 의미가 있지는 않은데, 정책 표현 메소드

2024-03-09 03:05 UTC, devxb commented on src/main/kotlin/domain/feedback/Feedback.kt
> +    }
[709a886](https://github.com/depromeet/na-lab-server/pull/395/commits/709a886c9f509b98b5002f14ef054cfda85a5327)

2024-03-09 03:05 UTC, devxb commented on src/main/kotlin/domain/feedback/ChoiceFormQuestionFeedback.kt
> +    bookmark: domain.feedback.Bookmark = domain.feedback.Bookmark.Companion.impossible(),
이것도 수정완료~ 위에있떤 패키지 이상하게 옮기면서 생긴거

[a72fa11](https://github.com/depromeet/na-lab-server/pull/395/commits/a72fa11fb0477387fefb0926fdc877ca734f6d61)

2024-03-09 03:07 UTC, devxb commented on src/main/kotlin/domain/feedback/FormQuestionFeedbackable.kt
> +    open val id: Long,
kotlin jpa 쓸때, abstract class 에 `@Entity` 걸면 
org.hibernate.HibernateException: Getter methods of lazy classes cannot be final:
이 에러 떠서 final인거 open으로 풀어줘야해서 해놨으

2024-03-09 03:07 UTC, devxb commented on src/main/kotlin/domain/feedback/value/NickName.kt
> +) {
[12d8b2c](https://github.com/depromeet/na-lab-server/pull/395/commits/12d8b2c92633b4d329fafb8e8b6d99fab29abbc3)

수정완료

2024-03-09 03:34 UTC, devxb commented on src/main/kotlin/domain/feedback/value/NickName.kt
> +        }
[bd06dee](https://github.com/depromeet/na-lab-server/pull/395/commits/bd06dee83f6391601cff6930a30ce05684e22f9a)

2024-03-09 03:36 UTC, devxb commented on src/main/kotlin/domain/survey/Choice.kt
> +    }
[c1db249](https://github.com/depromeet/na-lab-server/pull/395/commits/c1db249ebb705d8a53992e26eeb1b098e45b1fc1)

2024-03-09 03:43 UTC, devxb commented on src/main/kotlin/domain/survey/value/ImageUrl.kt
> +class ImageUrl(
12af3b4

survey domain vo들 전부 valueclass로 수정했어

2024-03-09 03:45 UTC, devxb commented on src/main/kotlin/domain/survey/FormQuestionable.kt
> +    override fun compareTo(other: FormQuestionable): Int {
[f32ad3e](https://github.com/depromeet/na-lab-server/pull/395/commits/f32ad3e708c136626731784bfaf6a97b788ea808)

2024-03-09 03:50 UTC, devxb commented on src/main/kotlin/domain/survey/ChoiceFormQuestion.kt
> +    }
https://github.com/depromeet/na-lab-server/blob/main/survey/survey-domain/src/main/java/me/nalab/survey/domain/survey/valid/ChoiceFormQuestionValidator.java

validator에 static으로 빠져있던거를 객체 자신이 검사하게 수정한거긴한데 
원래 있던 메소드로 돌리면서 없애겠음

2024-03-09 03:50 UTC, devxb commented on src/main/kotlin/domain/survey/Survey.kt
> +    private fun validNoDuplicatedFormOrder() {
https://github.com/depromeet/na-lab-server/blob/main/survey/survey-domain/src/main/java/me/nalab/survey/domain/survey/valid/SurveyValidator.java

이것도 이거를 Survey안으로 옮긴거 마찬가지로 메소드 돌리면서 없애겠음

2024-03-09 03:51 UTC, devxb commented on src/main/kotlin/domain/survey/Target.kt
> +        private val NONE_BOOKMARKED_SURVEYS: MutableSet<SurveyBookmark> = HashSet()
북마크 되지 않은 기본 상태 표현용으로 네이밍 매직넘버 지우는느낌

2024-03-09 14:27 UTC, dojinyou commented on src/main/kotlin/domain/feedback/FormQuestionFeedbackable.kt
> +    open val id: Long,
이거 여기서 명시적으로 쓰지 말고 그 kotlin jpa 관련 플러그인 있지 않나 끄거 쓰면 되지 않아?

2024-03-09 14:43 UTC, devxb commented on src/main/kotlin/domain/feedback/FormQuestionFeedbackable.kt
> +    open val id: Long,
아 그래??? kotlin r2dbc밖에 안써봐서 몰랐네
찾아보고 바꾸겠음

2024-03-09 15:02 UTC, dojinyou commented on src/main/kotlin/me/nalab/api/survey/domain/survey/Target.kt
> +    }
이거는 멀티 쓰레드 환경에서 동시성 문제 없나??

2024-03-09 15:02 UTC, dojinyou commented on src/main/kotlin/me/nalab/api/survey/domain/survey/value/ImageUrl.kt
> +        fun empty(): ImageUrl = ImageUrl("")
요거는 왜!?

2024-03-09 15:02 UTC, dojinyou commented on src/test/java/me/nalab/api/survey/domain/feedback/value/NickNameTest.kt
> +internal class NickNameTest : DescribeSpec({
👍

2024-03-09 15:03 UTC, dojinyou commented on src/main/kotlin/domain/feedback/Bookmark.kt
> +            domain.feedback.Bookmark(bookmarkedAt = TimeUtil.toInstant())
음...  잘 모르겠음 표현이 되는건지? 
`ChoiceFormQuestion는 북마크 할 수 없다.`를  어디서 알 수 있는거임?

2024-03-10 01:09 UTC, devxb commented on gradle/migration.gradle
> +    apply plugin: 'io.spring.dependency-management'
gallery도메인 개발할때 생성한 kotlin.gradle에 전역적으로 설정되어있어서 괜찮을거 같아

2024-03-10 01:10 UTC, devxb commented on src/main/kotlin/me/nalab/api/core/TimeBaseEntity.kt
> +        updatedAt = if (updatedAt != null) updatedAt else Instant.now()
[98b3ac5](https://github.com/depromeet/na-lab-server/pull/395/commits/98b3ac5ac026360912766f11036c2fc362bab565)

수정 완료

2024-03-10 01:11 UTC, devxb commented on src/main/kotlin/me/nalab/api/core/TimeUtil.kt
> +class TimeUtil private constructor() {
[9123154](https://github.com/depromeet/na-lab-server/pull/395/commits/9123154544d448ca4de1d9a02e1c083e4570de04)

수정완료

2024-03-10 01:13 UTC, devxb commented on src/main/kotlin/me/nalab/api/survey/domain/feedback/Feedback.kt
> +            compareByDescending<Feedback> { it.updatedAt }.thenByDescending { it.createdAt }
[c05bd80](https://github.com/depromeet/na-lab-server/pull/395/commits/c05bd80cc87e91e22088c2270dffeebb39a2c04e)

수정완료

2024-03-10 01:15 UTC, devxb commented on src/main/kotlin/me/nalab/api/survey/domain/survey/Target.kt
> +    }
[9253af7](https://github.com/depromeet/na-lab-server/pull/395/commits/9253af7aadcbe7ca7b0e8ee42b9a5ffdda5f8998)

발생할거 같아서 새롭게 생성하는 방향으로 수정했어

2024-03-10 01:16 UTC, devxb commented on src/main/kotlin/me/nalab/api/survey/domain/survey/value/ImageUrl.kt
> +        fun empty(): ImageUrl = ImageUrl("")
이거도 지금 정책이 "이미지가 없으면 직군별 기본 이미지" 를 내려주는거라서 empty로 만들어놨으

2024-03-10 01:19 UTC, devxb commented on src/main/kotlin/domain/feedback/Bookmark.kt
> +            domain.feedback.Bookmark(bookmarkedAt = TimeUtil.toInstant())
ChoiceFormQuestion에서 이렇게 표현하고 있긴한데, impossible이 정의된 Bookmark랑 사용하는위치가 멀어서 잘 안보이는건가?

<img width="759" alt="스크린샷 2024-03-10 오전 10 17 24" src="https://github.com/depromeet/na-lab-server/assets/62425964/c5f28e0b-1eb3-4b6c-b98d-33715bcc71d4">

2024-03-11 02:39 UTC, dojinyou commented on src/main/kotlin/domain/feedback/Bookmark.kt
> +            domain.feedback.Bookmark(bookmarkedAt = TimeUtil.toInstant())
null 넣고 bookmark 관련 메서드들 호출되면 무시하거나 에러 발생하게 하는게 더 좋을 것 같은데?

2024-03-11 02:40 UTC, dojinyou commented on src/main/kotlin/me/nalab/api/survey/domain/survey/value/ImageUrl.kt
> +        fun empty(): ImageUrl = ImageUrl("")
nullable하게 처리하는 건 별루?

2024-03-11 02:47 UTC, dojinyou approved these changes
기존 코멘트 내용 빼고 요것만 반영하면 될듯

2024-03-11 02:47 UTC, dojinyou commented on src/main/kotlin/me/nalab/api/core/TimeUtil.kt
> +        }
val로 쓰고 if statement 로 처리하기
```suggestion
        val current = if (clock == null) Instant.now() else Instant.now(clock)
```

2024-03-11 02:47 UTC, dojinyou commented on src/main/kotlin/me/nalab/api/core/TimeUtil.kt
> +    fun fixed(clock: Clock?) {
fixed 할 때는 not null type으로 받기
```suggestion
    fun fixed(clock: Clock) {
```

2024-03-11 02:47 UTC, dojinyou commented on src/main/kotlin/me/nalab/api/core/TimeUtil.kt
> +            .withZone(ZoneId.of("UTC"))
요건 매번 생성하지 말고 기본 필드로 가지고 있어도 될듯!

2024-03-11 02:47 UTC, dojinyou commented on src/main/kotlin/me/nalab/api/core/TimeUtil.kt
> +    fun toInstant(): Instant {
now 메서드명 그대로 쓰기?!
```suggestion
    fun now(): Instant {
```

2024-03-11 02:47 UTC, dojinyou commented on src/main/kotlin/me/nalab/api/core/TimeBaseEntity.kt
> +        val now = Instant.now()
TimeUtil.now() 사용하기

2024-03-11 02:47 UTC, dojinyou commented on src/main/kotlin/me/nalab/api/core/TimeBaseEntity.kt
> +        updatedAt = Instant.now()
ditto

2024-03-12 03:38 UTC, devxb commented on src/main/kotlin/me/nalab/api/core/TimeBaseEntity.kt
> +        val now = Instant.now()
[842a1fa](https://github.com/depromeet/na-lab-server/pull/395/commits/842a1faeccdf1999d5ab3c0cbfbafb8f9a607d5c)

2024-03-12 03:38 UTC, devxb commented on src/main/kotlin/me/nalab/api/core/TimeBaseEntity.kt
> +        updatedAt = Instant.now()
[842a1fa](https://github.com/depromeet/na-lab-server/pull/395/commits/842a1faeccdf1999d5ab3c0cbfbafb8f9a607d5c)

2024-03-12 03:38 UTC, devxb commented on src/main/kotlin/me/nalab/api/core/TimeUtil.kt
> +    fun toInstant(): Instant {
[35907de](https://github.com/depromeet/na-lab-server/pull/395/commits/35907dee91a29bdd9577d291dbcb556fed564c85)

2024-03-12 03:38 UTC, devxb commented on src/main/kotlin/me/nalab/api/core/TimeUtil.kt
> +            .withZone(ZoneId.of("UTC"))
[55478a4](https://github.com/depromeet/na-lab-server/pull/395/commits/55478a458b629838ed4cc58796577c70dd6d89b1)

2024-03-12 03:39 UTC, devxb commented on src/main/kotlin/me/nalab/api/core/TimeUtil.kt
> +    fun fixed(clock: Clock?) {
[bcc6961](https://github.com/depromeet/na-lab-server/pull/395/commits/bcc696122032b778fab1f939f835fb656a70b38a)

2024-03-12 03:39 UTC, devxb commented on src/main/kotlin/me/nalab/api/core/TimeUtil.kt
> +        }
[6bfa224](https://github.com/depromeet/na-lab-server/pull/395/commits/6bfa2249fd1e70d57d229621a0c44698cc14695c)

2024-03-12 03:40 UTC, merged