feat: User 삭제 API 개발
depromeet/na-lab-server pull request #405
Opened 2024-03-08 13:35 UTC by devxb

## 어떤 기능을 개발했나요?
token을 받아서 유저를 삭제하는 API를 개발했습니다.

## 어떻게 해결했나요?
- [x] token에 해당하는 유저 삭제 API 개발
- [x] UserOauthInfoEntity, UserEntity 삭제
	- (유저 삭제되면 다음 로그인 email, provider 를 받을때 새로운 유저로 가입되어서 중복조회 발생 x)
    - (target 찾을때, 위 이유 때문에 삭제되면 같은 타겟 안나옴)
- [x] 인수테스트 작성

## 이슈 넘버
- close #404 

## 참고자료

2024-03-08 17:49 UTC, dojinyou requested changes

2024-03-08 17:49 UTC, dojinyou commented on user/user-application/src/main/java/me/nalab/user/application/service/UserDeleteService.java
> +    }
토큰이 여기까지 넘어와서 이렇게 쪼개지는 건 의미 알기가 너무 어려운듯

2024-03-08 17:49 UTC, dojinyou commented on user/user-jpa-adapter/src/main/java/me/nalab/user/jpa/adaptor/create/repository/UserOAuthInfoJpaRepository.java
> +    void deleteByUserId(@Param("userId") Long userId);
이거 update row 0개 여도 에러 안 발생하는거지?

2024-03-09 04:11 UTC, devxb commented on user/user-jpa-adapter/src/main/java/me/nalab/user/jpa/adaptor/create/repository/UserOAuthInfoJpaRepository.java
> +    void deleteByUserId(@Param("userId") Long userId);
저 메소드는 안던지는데
JPA에서 만들어주는 메소드가 던지길래 검증 로직 추가했어

[9753ea3](https://github.com/depromeet/na-lab-server/pull/405/commits/9753ea3856b9853dd0886825847fc7121adba593)

아래는 없으면 ignore 한다 되어있는데 테스트해보니까 예외던짐
<img width="615" alt="스크린샷 2024-03-09 오후 1 02 10" src="https://github.com/depromeet/na-lab-server/assets/62425964/53f9b723-89c7-437d-8633-acee0e71c80c">

2024-03-09 04:12 UTC, devxb commented on user/user-application/src/main/java/me/nalab/user/application/service/UserDeleteService.java
> +    }
[e78b278](https://github.com/depromeet/na-lab-server/pull/405/commits/e78b278cd3365be857310ac3284379c5fe0cee16)

인터셉터에서 token끊고 requestAttribute로 받는 방향으로 수정했음

2024-03-09 04:12 UTC, devxb commented on user/user-web-adaptor/src/main/java/me/nalab/user/web/adaptor/logined/DeleteUserController.java
> +    }
[e78b278](https://github.com/depromeet/na-lab-server/pull/405/commits/e78b278cd3365be857310ac3284379c5fe0cee16)

2024-03-09 15:09 UTC, dojinyou approved these changes
`bearer` Authentication header prefix 같은 걸로 정리되면 좋을 것 같음.

2024-03-10 01:44 UTC, devxb commented
enum으로 관리하는거로 수정해서 머지할께

2024-03-10 01:44 UTC, merged