[fix] : questions를 order로 정렬해서 반환
depromeet/na-lab-server pull request #67
Opened 2023-05-21 10:19 UTC by ssssujini99

## 어떤 기능을 개발했나요?
질문 폼 조회 usecase에
survey 반환 시에, survey의 모든 질문들을 지정된 order에 맞게 반환하는 로직을 추가했습니다

## 어떻게 해결했나요?

## 참고자료

2023-05-21 10:20 UTC, devxb commented
이거 sqaush merge 해야할거 같아요

base branch로 어떠한 squash merge도 없는상태에서 base -> main 으로 rebase merge하면 관련 pr 같은게 안보이더라구요

2023-05-21 10:21 UTC, ssssujini99 commented
요렇게 바꾸면 될까요..?

2023-05-21 10:21 UTC, devxb commented
네네 맞아용 아래 스쿼시머지 누르는거 주의하세요! 저도 오늘 실수한번해서 ㅎ,,,

2023-05-21 10:26 UTC, ssssujini99 commented
아아 넵 이해했습니다!!
무조건 feature에서 작업 후 base로 squash merge 후
base에서 main으로 rebase merge ,,,,, 암기 암기

항상 feature부터 파서 작업해야겠어요

2023-05-21 10:36 UTC, dojinyou requested changes

2023-05-21 10:36 UTC, dojinyou commented on survey/application/src/main/java/me/nalab/survey/application/service/find/SurveyFindService.java
> +		survey.getFormQuestionableList().sort(Comparator.comparing(FormQuestionable::getOrder));
이 정렬방식으로 FormQuestionable에 구현해야될 것 같아요!
객체의 기본적인 정렬전략일 경우 Comparable을 구현하기!

2023-05-21 10:36 UTC, dojinyou commented on survey/application/src/test/java/me/nalab/survey/application/service/find/SurveyFindServiceTest.java
> +		assertEquals(true, isSortedByOrder);
기본 정렬 방식에 대한 테스트는 구현되어 있는 것에 대한 테스트로 구체적인 로직(앞에 있는 element가 order가 더 작은지!)를 체크하면 좋을 것 같아요! 사용하는 곳에서는 따로 테스트 안해도 될 것 같네요!

2023-05-21 10:40 UTC, ssssujini99 commented on survey/application/src/main/java/me/nalab/survey/application/service/find/SurveyFindService.java
> +		survey.getFormQuestionableList().sort(Comparator.comparing(FormQuestionable::getOrder));
아하 넵 저도 이건 기본적인 정렬전략이라고 생각합니다
그래서 Comparable을 정의하고 이 부분에서는 sort를 해주면 될 것 같습니다..!!
@devxb 준영님은 어떠신가요? 준영님도 맞다고 생각하시면 제가 FormQuestionable에 Comparator 넣고 수정마무리하겠습니다!!

2023-05-21 11:21 UTC, devxb commented on survey/application/src/main/java/me/nalab/survey/application/service/find/SurveyFindService.java
> +		survey.getFormQuestionableList().sort(Comparator.comparing(FormQuestionable::getOrder));
넵넵 저도 동의합니다!
도메인에서, order -> updatedAt -> createdAt 기준으로 정렬되는 Comparable 구현해야할거 같아요!

2023-05-21 12:50 UTC, dojinyou commented on survey/application/src/main/java/me/nalab/survey/application/service/find/SurveyFindService.java
> +		survey.getFormQuestionableList().sort(FormQuestionable::compareTo);
요거 혹시 sort() 이렇게만 해도 되지 않나요?! 안되나요!?

2023-05-21 12:50 UTC, dojinyou commented on survey/application/src/test/java/me/nalab/survey/application/service/find/SurveyFindServiceTest.java
> +			.isPresent();
```suggestion
		var formQuestionList = result.getFormQuestionDtoableList();
		boolean isAscendingOrder = IntStream().range(0, formQuestionList.size() - 1).allMatch(i -> {
			var prev = formQuestionList.get(i);
			var current = formQuestionList.get(i + 1);

			return prev.compareTo(current) < 0;
		});
```

이런 식으로 짜도 될 것 같아요!

2023-05-21 12:50 UTC, dojinyou commented on survey/domain/src/main/java/me/nalab/survey/domain/survey/FormQuestionable.java
> +			.compare(this, other);
```suggestion
		return Integer.compare(this, other);
```

2023-05-21 15:28 UTC, ssssujini99 commented on survey/application/src/main/java/me/nalab/survey/application/service/find/SurveyFindService.java
> +		survey.getFormQuestionableList().sort(FormQuestionable::compareTo);
네 sort() 에 무조건 comparator 인자가 들어가야하더라구요..!!

2023-05-21 15:32 UTC, ssssujini99 commented on survey/domain/src/main/java/me/nalab/survey/domain/survey/FormQuestionable.java
> +			.compare(this, other);
Integer.compare(this, other)로만은 안되는 것 같아요..!!
저게 FormComparable에서 other를 꺼내준 다음에 비교해야 하는 것 같습니당

2023-05-21 15:39 UTC, ssssujini99 commented on survey/application/src/test/java/me/nalab/survey/application/service/find/SurveyFindServiceTest.java
> +			.isPresent();
아하 그 저희 도메인 상에서 comparable을 구현했습니다 (정책이라고 생각해서!)
그래서 dto에는 comparable이 구현되어있지가 않습니다..!!
그래서 도메인에서 -> dto로 변환 이후에 dto에서 값 비교하는 test라 (어플리케이션부분의 test로 domain 에서 dto로 반환 이후입니다)
그래서 dto에서는 compareTo 를 적용하지 못할 것 같아요!

2023-05-21 16:48 UTC, devxb commented on survey/application/src/main/java/me/nalab/survey/application/service/find/SurveyFindService.java
> +		survey.getFormQuestionableList().sort(FormQuestionable::compareTo);
음,,,, 근데 정렬해주는 로직이 usecase에 있는게 아니라 도메인에 있어야 하지 않나요.?!
생성시점에 제가 중복 order검사 하는거 처럼 생성시점에 자동으로 정렬되게끔 해주는게 좋아보입니다..! 
이유는 정책이라 도메인에 로직이 있어야하고, 모든 usecase에서 정렬 되어있는 order를 공유해야 하니까?!

2023-05-21 16:51 UTC, devxb commented on survey/application/src/main/java/me/nalab/survey/application/service/find/SurveyFindService.java
> +		survey.getFormQuestionableList().sort(FormQuestionable::compareTo);
아..! 그리고 Comparable이 구현되어 있으면 Collections.sort()로 Comparator없이 사용 가능합니다!

<img width="461" alt="스크린샷 2023-05-22 오전 1 50 39" src="https://github.com/depromeet/na-lab-server/assets/62425964/38fb881d-8737-4619-a45e-1eed0e9cc6ab">

2023-05-21 17:00 UTC, devxb commented on survey/application/src/test/java/me/nalab/survey/application/service/find/SurveyFindServiceTest.java
> +			.isPresent();
```suggestion
		result.getFormQuestionDtoableList().stream().
		.map(FormQuestionDtoable::getOrder)
		.reduce((prve, current) -> assertTrue(prev < current));
```

이런방식은 안되나요? 
예외에서 RuntimeException을 던지면 어떤 값에서 에러가나오는지 판단하기가 힘들다?

2023-05-21 17:02 UTC, devxb commented on survey/application/src/test/java/me/nalab/survey/application/service/find/SurveyFindServiceTest.java
> +			.isPresent();
예외를 던지면 isAscendingOrder가 false가 되는상황이 없을거 같아요..!

2023-05-21 18:19 UTC, ssssujini99 commented on survey/application/src/main/java/me/nalab/survey/application/service/find/SurveyFindService.java
> +		survey.getFormQuestionableList().sort(FormQuestionable::compareTo);
아 아예 생성시점에 넣는다는 말씀이신가용?

2023-05-21 18:20 UTC, ssssujini99 commented on survey/application/src/main/java/me/nalab/survey/application/service/find/SurveyFindService.java
> +		survey.getFormQuestionableList().sort(FormQuestionable::compareTo);
넵 아예 생성시점에 만들어버리면 ? 조회할때는 그냥 단순히 꺼내오기만 하면 되겠네요...!!

2023-05-21 18:24 UTC, ssssujini99 commented on survey/application/src/main/java/me/nalab/survey/application/service/find/SurveyFindService.java
> +		survey.getFormQuestionableList().sort(FormQuestionable::compareTo);
생성시점이 맞는 것 같아요.... 조회할때마다 매번 정렬시키는게 이상하네요 ㅋㅋㅋㅋ

2023-05-21 18:25 UTC, ssssujini99 commented on survey/application/src/main/java/me/nalab/survey/application/service/find/SurveyFindService.java
> +		survey.getFormQuestionableList().sort(FormQuestionable::compareTo);
아 이걸 인수테스트 짜다가 발견했어요.. 다음부터는 인수테스트부터 짜야할 것 같습니다 ㅋㅋ ㅠㅠ 놓치는게 많았네요 😓🤧

2023-05-22 02:15 UTC, dojinyou commented on survey/domain/src/main/java/me/nalab/survey/domain/survey/FormQuestionable.java
> +			.compare(this, other);
getOrder 값이 Integer인 거 같아서! 비교할 때 this.getOrder(), other.getOrder() 만 추가하면 될거라고 생각했어요! ㅋㅋ 코드가 좀 틀렸네요!

2023-05-22 02:16 UTC, dojinyou commented on survey/application/src/test/java/me/nalab/survey/application/service/find/SurveyFindServiceTest.java
> +			.isPresent();
이렇게 해도 상관은 없을 것 같네요! 단점이라면 뒤에 몇개의 문제가 있는 지 한번의 테스트로 파악할 수 없다 정도?

2023-05-22 03:03 UTC, devxb commented on survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
> +		return choiceList.stream()
질문) 이거 시간복잡도가 어떻게 되죠????
Collections.sort() -> 복사로직 없음 : nlogn
.collect(Collectors.toList()) -> ??

2023-05-22 03:09 UTC, ssssujini99 commented on survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
> +		return choiceList.stream()
두 가지 경우의 수가 있습니다

1 > 질문들을 일단 다 리스트로 받은 다음 마지막에 정렬 수행 (현재 제 코드와 같습니다)
2 > 넣을 때마다 정렬하기

1의 시간복잡도는 nlogn * n = n^2 logn 입니다
2의 시간복잡도는 n*n = n^2 입니다

2023-05-22 03:09 UTC, devxb commented on survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
> +	}
```suggestion
	private void withSortedChoiceList(List<Choice> choiceList) {
		Collections.sort(choiceList);
	}
```

2023-05-22 03:11 UTC, devxb commented on survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
> +		return choiceList.stream()
앗 질문이 잘못되었네요! ㅠㅠ

stream() 마지막에 .collect(toList()) 연산이 값 복사가 일어나는거로 알고있어서..! 정렬된 값이 참조가 아니라 복사되지 않을까(불필요한 O(n))? 라는 걱정을 했습니다!

2023-05-22 03:13 UTC, devxb commented on survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
> +		return choiceList.stream()
스트림은 불변으로 동작해서, 스트림 대상 객체에 수정을 가하지 않는거로 알고있습니다..! 그래서 .collect(toList()) 도 복사가 일어나지 않을까? 했는데, 복사가 일어나는거 같네요 

[hudi님](https://github.com/devHudi)
<img width="705" alt="스크린샷 2023-05-22 오후 12 12 17" src="https://github.com/depromeet/na-lab-server/assets/62425964/937ce443-7a61-4142-8566-c9d890bf03d8">

2023-05-22 03:17 UTC, ssssujini99 commented on survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
> +	}
요렇게 바꾸겠습니다!!

2023-05-22 03:18 UTC, ssssujini99 commented on survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
> +	}
이렇게 했을 경우 logN 으로 처리할 수 있네요!! 굿

2023-05-22 06:54 UTC, ssssujini99 commented on survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
> +		return choiceList.stream()
네넵 맞아요..! 그래서 O(N) 이 마지막에 추가됩니다

2023-05-22 06:54 UTC, ssssujini99 commented on survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
> +		return choiceList.stream()
그래서 Collections.sort() 로 모두 변경했습니다!!

2023-05-22 06:54 UTC, ssssujini99 commented on survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
> +		return choiceList.stream()
O(logN) 으로 끝나게끔?

2023-05-22 07:01 UTC, ssssujini99 commented
FormQuestionable과 Choice에 comparator 추가와 해당 테스트까지 추가했고,

Survey랑 ChoiceFormQuestion 생성자에 Collections.sort() 넣었습니다.
스트림으로 돌며 toCollectList() 로 하려고 했으나, 위에서 준영님 말씀대로 이게 복사라 불필요한 O(N) 연산이 추가됩니다..
그래서 그냥 Collections.sort() 를 이용했습니다! (어차피 원본 값이 필요 없고, 정렬된 값이 필요한 거니까)
그 정렬을 생성시점에 정렬시키도록 하였습니다
그리고 이거에 대한 테스트도 하나 추가했습니다

이게 스트림으로 돌리고 toCollectList 가 아니라 해당 객체 정렬이라 List.of() 불변객체를 생성하면 안되는 이슈가 있어서
그거에 대한 기존 테스트들이랑 fixture 다 ArrayList로 수정해놓았습니다

최종 확인해주시면 감사하겠습니다 😆

2023-05-22 08:05 UTC, devxb commented
@ssssujini99 

> Survey랑 ChoiceFormQuestion 생성자에 Collections.sort() 넣었습니다. 스트림으로 돌며 toCollectList() 로 하려고 했으나, 위에서 준영님 말씀대로 이게 복사라 불필요한 O(N) 연산이 추가됩니다.. 그래서 그냥 Collections.sort() 를 이용했습니다! (어차피 원본 값이 필요 없고, 정렬된 값이 필요한 거니까) 그 정렬을 생성시점에 정렬시키도록 하였습니다 그리고 이거에 대한 테스트도 하나 추가했습니다
> 
> 이게 스트림으로 돌리고 toCollectList 가 아니라 해당 객체 정렬이라 List.of() 불변객체를 생성하면 안되는 이슈가 있어서 그거에 대한 기존 테스트들이랑 fixture 다 ArrayList로 수정해놓았습니다
> 
> 최종 확인해주시면 감사하겠습니다 😆
> 
> (이 pr이 이렇게 커질 줄 몰랐네요.. ㅠ 그래서 커밋 세세히 나눠놓았습니다 ㅠ_ㅠ)

수고하셨습니다 👍
제가 댓글단거중에 해결된거 전부 resolve 해놨습니다! 이제, 테스트만 수정되면 저는 더 없는거 같아요

2023-05-22 09:43 UTC, dojinyou approved these changes

2023-05-22 09:43 UTC, merged