[test] : 질문 폼의 피드백 요약 인수테스트 작성
depromeet/na-lab-server pull request #88
Opened 2023-05-23 11:28 UTC by ssssujini99

## 어떤 기능을 개발했나요?
질문 폼의 피드백 요약 (해당 전체 피드백 수와 읽지 않은 피드백의 수) API에 대한 인수테스트를 작성했습니다

- [x]  /feedback/findsummary 패키지에 질문 폼의 피드백 요약 `인수테스트` 클래스를 생성했습니다
- [x] `FeedbackAcceptanceValidator` 에 요청로직에 대한 validation 로직을 추가했습니다 -> `assertIsFeedbackSummaryFound`
- [x] `AbstractFeedbackTestSupporter` 에 요청로직을 추가했습니다 -> `findFeedbackSummary` 

## 어떻게 해결했나요?

## 참고자료

2023-05-23 11:51 UTC, devxb requested changes

2023-05-23 11:51 UTC, devxb commented on api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
>  	//: TODO 여기에 Feedback api관련된 호출 메소드를 만들어 주세요. AbstractSurveyTestSupporter 참고해서 작성하면 됩니다.
아 이거는 지워주셔도 됩니다 ㅋㅋㅋㅋㅋㅋ
나중에 수정해주세요 아니면 제 쪽에서 저 주석 지워서 없어질지도 모르겠네요 main 합칠때

2023-05-23 11:51 UTC, devxb commented on api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
> +	//: TODO
이것ㅅ도요 주석!

2023-05-23 11:51 UTC, devxb commented on api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
> +	//: TODO
이 주석도 지워주세요 :)

2023-05-23 11:51 UTC, devxb commented on api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/findsummary/FeedbackFindSummaryAcceptanceTest.java
> +
생성이 없는거는 피드백 생성 api가 안나와서 그런건가용??

아직 없더라도..! /v1/feedbacks?survey-id={survey_id} 이렇게 호출하는거로 호출로직은 만들 수 있을거 같아요

2023-05-24 12:01 UTC, dojinyou approved these changes

2023-05-25 08:14 UTC, ssssujini99 commented on api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/findsummary/FeedbackFindSummaryAcceptanceTest.java
> +
굳이 피드백 생성을 호출 안해도 될 것 같아서 안넣었습니다!!

2023-05-25 09:08 UTC, closed without merging